apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: my-php-app
        image: 706274417810.dkr.ecr.ap-south-1.amazonaws.com/python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-svc
spec:
  selector:
    app: php-app
  ports:
    ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: php-app
